title: CryptoPoules - Low fee, reliable staking pools
description: Delegate your ADA in our Cardano staking poules. Oops, we meant POOLS.

socials:
  reddit: https://reddit.com/r/cryptopoules
  twitter: https://twitter.com/cryptopoules
