name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - run: bundle exec jekyll build --future --verbose
      env:
        JEKYLL_ENV: production
        NODE_ENV: production 
    - uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: _site
